### ISSUE TITLE
Refactor unit tests to use configuration based static test data

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/vagrant-service-manager#370]
Hi,

Most of the unit tests are using test data which are repeated quite often. Mostly there are repeated per test file.
One approach would be to use locale based data, where each test data can be arranged and used.

Example

```
# yaml
test_feature1:
   url: service_url
   version: default_test_version

# can be used in test file repeatedly as
I18n.t('test_feature1.url') 
I18n.t('test_feature1.version') 
```

Any other suggestion are also welcome.
