### ISSUE TITLE
Integrate with Appveyor to build and test on Windows

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/vagrant-service-manager#433]
This should pretty much do it:

```

---
version: "{build}"
branches:
  only:
    - master
install:
  - set PATH=C:\Ruby200\bin;%PATH%
  - ruby --version
  - gem --version
  - gem uninstall -x bundler
  - gem install bundler -v 1.12.5
  - bundler --version
  - bundle install
build_script:
  - bundle exec rake clean install
test_script:
  - bundle exec rake rubocop test TESTOPTS="-v"
artifacts:
  - path: pkg\*.gem
```
